name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install python3 python3-pip -y
            pip3 install numpy tensorflow matplotlib jupyter
            sudo ufw allow 8888
            jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser
            # Якщо репозиторій уже є, оновлюємо його. Якщо ні — клонуємо
            if [ -d "laba443" ]; then
              cd laba443
              git pull origin main
            else
              git clone https://github.com/VADUMr/laba223.git
              cd laba443
            fi
            echo 'Deployment successful to digital ocean d1' 
          
